apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: concourse-db
spec:
  version: "10.2-v2"
  storageType: Durable
  replicas: 1
  storage:
    storageClassName: do-block-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate