apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: keycloak
spec:
  version: "10.2-v2"
  storageType: Durable
  storage:
    storageClassName: "do-block-storage"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
