{
 "title": "Minecraft",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mc_players_total", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Players Online",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mc_players_total{state=\"online\"}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mc_jvm_memory{type='max'} - scalar(mc_jvm_memory{type='free'})"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mc_tps" }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mc_loaded_chunks_total", "legendFormat": "{{world}}" }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "mc_jvm_memory{type='max'}", "legendFormat": "Allocated" },
    {
     "expr": "mc_jvm_memory{type='max'} - scalar(mc_jvm_memory{type='free'})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mc_entities_total", "legendFormat": "{{world}}_total" },
    { "expr": "mc_living_entities_total", "legendFormat": "{{world}}_living" }
   ]
  },
  {
   "title": "Tickrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "mc_tps", "legendFormat": "TPS" }
   ]
  },
  {
   "title": "Server-Side View Distance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "minecraft_view_distance", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}