---
resource_types:
  - name: helm
    type: docker-image
    source:
      repository: linkyard/concourse-helm-resource
  
  - name: discord
    type: docker-image
    source:
      repository: trivigy/discord-resource

resources:
  - name: kube-iac-prometheus
    type: git
    source:
      uri: git@github.com:hreeder/kube-iac.git
      private_key: |
        ((github.deploy_key))
      watch:
        - helm-apps/prometheus.yaml
    
  - name: kube-iac-grafana
    type: git
    source:
      uri: git@github.com:hreeder/kube-iac.git
      private_key: |
        ((github.deploy_key))
      watch:
        - helm-apps/grafana.yaml

  - name: kube-iac-traefik
    type: git
    source:
      uri: git@github.com:hreeder/kube-iac.git
      private_key: |
        ((github.deploy_key))
      watch:
        - helm-apps/traefik.yaml

  - name: kube-cluster
    type: helm
    check_every: 999999h
    source:
      cluster_url: ((kube.cluster_url))
      cluster_ca: ((kube.cluster_ca))
      token: ((kube.token))
  
  - name: discord
    type: discord
    check_every: 999999h
    source:
      token: ((discord.token))

jobs:
  - name: prometheus
    plan:
      - get: kube-iac-prometheus
        trigger: true
      - put: kube-cluster
        params:
          chart: stable/prometheus
          release: prometheus
          values: kube-iac-prometheus/helm-apps/grafana.yaml
        on_success:
          put: discord
          params:
            channel: "((discord.channel_id))"
            color: 0x5CB85C
            title: "[Concourse] Helm App Deployed"
            message: |
              **Pipeline**: helm-apps
              **Job**: prometheus
              :airplane_departure: Prometheus has now been deployed/updated
        on_failure:
          put: discord
          params:
            channel: "((discord.channel_id))"
            color: 0xFF0000
            title: "[Concourse] Helm App FAILURE"
            message: |
              **Pipeline**: helm-apps
              **Job**: prometheus
              :airplane_departure: Prometheus has FAILED to deploy/update. ROLLING BACK.
  
  - name: grafana
    plan:
      - get: kube-iac-grafana
        trigger: true
      - put: kube-cluster
        params:
          chart: stable/grafana
          release: grafana
          values: kube-iac-grafana/helm-apps/grafana.yaml
        on_success:
          put: discord
          params:
            channel: "((discord.channel_id))"
            color: 0x5CB85C
            title: "[Concourse] Helm App Deployed"
            message: |
              **Pipeline**: helm-apps
              **Job**: grafana
              :airplane_departure: Grafana has now been deployed/updated
        on_failure:
          put: discord
          params:
            channel: "((discord.channel_id))"
            color: 0xFF0000
            title: "[Concourse] Helm App FAILURE"
            message: |
              **Pipeline**: helm-apps
              **Job**: grafana
              :airplane_departure: Grafana has FAILED to deploy/update. ROLLING BACK.

  - name: traefik
    plan:
      - get: kube-iac-traefik
        trigger: true
      - put: kube-cluster
        params:
          chart: stable/traefik
          release: traefik
          values: kube-iac-traefik/helm-apps/traefik.yaml
        on_success:
          put: discord
          params:
            channel: "((discord.channel_id))"
            color: 0x5CB85C
            title: "[Concourse] Helm App Deployed"
            message: |
              **Pipeline**: helm-apps
              **Job**: traefik
              :airplane_departure: Træfik has now been deployed/updated
        on_failure:
          put: discord
          params:
            channel: "((discord.channel_id))"
            color: 0xFF0000
            title: "[Concourse] Helm App FAILURE"
            message: |
              **Pipeline**: helm-apps
              **Job**: traefik
              :airplane_departure: Træfik has FAILED to deploy/update. ROLLING BACK.