---
resource_types:
  - name: helm
    type: docker-image
    source:
      repository: linkyard/concourse-helm-resource

resources:
  - name: kube-iac
    type: git
    source:
      uri: git@github.com:hreeder/kube-iac.git
      private_key: |
        ((github.deploy_key))

  - name: kube-cluster
    type: helm
    source:
      cluster_url: ((kube.cluster_url))
      cluster_ca: ((kube.cluster_ca))
      token: ((kube.token))

jobs:
  - name: prometheus
    plan:
      - get: kube-iac
        trigger: true
      - put: kube-cluster
        params:
          chart: stable/prometheus
          release: prometheus
          values: kube-iac/helm-apps/grafana.yaml
  
  - name: grafana
    plan:
      - get: kube-iac
        trigger: true
      - put: kube-cluster
        params:
          chart: stable/grafana
          release: grafana
          values: kube-iac/helm-apps/grafana.yaml

  - name: traefik
    plan:
      - get: kube-iac
        trigger: true
      - put: kube-cluster
        params:
          chart: stable/traefik
          release: traefik
          values: kube-iac/helm-apps/traefik.yaml