---
meta:
  name: prometheus-operator
  chart: stable/prometheus-operator
  extra:
    - grafana_dashboards/harry-all-nodes.yaml

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.tbrb.dev

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'mc_host'
      static_configs:
      - targets: ['survival.sorcerermjolnir.net:9100']