---
meta:
  name: prometheus-operator
  chart: stable/prometheus-operator
  extra:
    - grafana_dashboards/harry-all-nodes.yaml

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.tbrb.dev
