---
meta:
  name: traefik
  chart: stable/traefik
  namespace: kube-system

deploymentStrategy:
  type: Recreate

metrics:
  prometheus:
    enabled: true
    restrictAccess: true

service:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    service.beta.kubernetes.io/tbrb-test-annotation: "true"

deployment:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

proxyProtocol:
  enabled: true
  trustedIPs:
    - 10.0.0.0/8

rbac:
  enabled: true

ssl:
  enabled: true
  enforced: true

gzip:
  enabled: false

acme:
  enabled: true
  staging: false
  challengeType: dns-01
  email: harry@reeder.dev
  dnsProvider:
    name: cloudflare
    existingSecretName: traefik-cloudflare
